#!/usr/bin/env python3
"""Compare per-OS output fingerprints (cross-OS portability CI).

Reads fingerprint-<os>.txt (lines "sha256  basename") for each runner OS and reports
whether each output artifact is byte-identical across operating systems. Writes
portability-os.{txt,csv,tex} into --out (default: cwd).

  python compare_os.py <fingerprints_dir> ubuntu-latest macos-latest windows-latest [--out DIR]
"""
import argparse
import pathlib
import re


def load(path: pathlib.Path) -> dict:
    out = {}
    if path.exists():
        for line in path.read_text().splitlines():
            parts = line.split()
            if len(parts) >= 2 and re.fullmatch(r"[0-9a-f]{64}", parts[0]):
                out[parts[1]] = parts[0]
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("dir")
    ap.add_argument("oses", nargs="+")
    ap.add_argument("--out", default=".")
    args = ap.parse_args()

    d = pathlib.Path(args.dir)
    per = {o: load(d / f"fingerprint-{o}.txt") for o in args.oses}
    artifacts = sorted({a for m in per.values() for a in m})
    ref = args.oses[0]

    rows, all_identical = [], True
    for art in artifacts:
        shas = {o: per[o].get(art) for o in args.oses}
        identical = len({s for s in shas.values() if s}) == 1 and all(shas.values())
        all_identical = all_identical and identical
        rows.append((art, shas, identical))

    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    txt = [f"Cross-OS portability - output determinism across {len(args.oses)} operating systems",
           f"OSes: {', '.join(args.oses)}", ""]
    for art, shas, identical in rows:
        txt.append(f"  {art:24} {'IDENTICAL' if identical else 'DIVERGENT'}  {(shas[ref] or '<missing>')[:12]}")
    txt.append("")
    txt.append(f"All {len(artifacts)} output artifacts identical across all OSes: {all_identical}")
    (out / "portability-os.txt").write_text("\n".join(txt) + "\n")

    csv = ["artifact," + ",".join(args.oses) + ",identical"]
    for art, shas, identical in rows:
        csv.append(art + "," + ",".join((shas[o] or "MISSING")[:12] for o in args.oses) + f",{identical}")
    (out / "portability-os.csv").write_text("\n".join(csv) + "\n")

    tex = ["% GENERATED by compare_os.py - cross-OS portability table body rows",
           "% columns: artifact & <one per OS> & SHA-256 (short, reference OS)"]
    for art, shas, identical in rows:
        cells = " & ".join(r"\ding{51}" if shas[o] and shas[o] == shas[ref] else r"\ding{55}"
                           for o in args.oses)
        tex.append(f"\\texttt{{{art}}} & {cells} & \\texttt{{{(shas[ref] or '')[:10]}}} \\\\")
    (out / "portability-os-table.tex").write_text("\n".join(tex) + "\n")

    print("\n".join(txt))
    # 0 = all identical, 2 = diverged (a valid result, not a failure). Real errors
    # (missing files, exceptions) surface as exit 1 so CI can tell them apart.
    return 0 if all_identical else 2


if __name__ == "__main__":
    raise SystemExit(main())
