#!/usr/bin/env python3
"""Compare per-artifact output SHA-256 across distro containers (portability eval).

Reads results/<tag>.hashes (lines "sha256  basename") produced by run-portability.sh,
one file per distro, and reports whether each output artifact is byte-identical across
all distros. Writes eval_results/portability.{txt,csv,tex}.
"""
import pathlib
import re
import sys


def tag_of(image: str) -> str:
    return "carp-port-" + re.sub(r"[:/.]", "_", image)


def load(path: pathlib.Path) -> dict:
    out = {}
    for line in path.read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2 and re.fullmatch(r"[0-9a-f]{64}", parts[0]):
            out[parts[1]] = parts[0]
    return out


def main() -> int:
    results = pathlib.Path(sys.argv[1])
    images = sys.argv[2:]
    if not images:
        images = sorted(p.stem.replace("carp-port-", "") for p in results.glob("*.hashes"))

    per = {img: load(results / f"{tag_of(img)}.hashes") for img in images}
    artifacts = sorted({a for m in per.values() for a in m})
    ref = images[0]

    rows = []
    all_identical = True
    for art in artifacts:
        shas = {img: per[img].get(art) for img in images}
        identical = len({s for s in shas.values() if s}) == 1 and all(shas.values())
        all_identical = all_identical and identical
        rows.append((art, shas, identical))

    eval_results = pathlib.Path(__file__).resolve().parents[2] / "eval_results"
    eval_results.mkdir(parents=True, exist_ok=True)

    # human report
    txt = [f"Portability eval - output determinism across {len(images)} Linux distros",
           f"Distros: {', '.join(images)}", ""]
    for art, shas, identical in rows:
        txt.append(f"  {art:24} {'IDENTICAL' if identical else 'DIVERGENT'}  "
                   f"{(shas[ref] or '<missing>')[:12]}")
    txt.append("")
    txt.append(f"All {len(artifacts)} output artifacts identical across all distros: {all_identical}")
    (eval_results / "portability.txt").write_text("\n".join(txt) + "\n")

    # csv
    csv = ["artifact," + ",".join(images) + ",identical"]
    for art, shas, identical in rows:
        csv.append(art + "," + ",".join((shas[i] or "MISSING")[:12] for i in images) + f",{identical}")
    (eval_results / "portability.csv").write_text("\n".join(csv) + "\n")

    # latex table body (paper-ready): a check where a distro matches the reference hash
    tex = ["% GENERATED by compare_hashes.py - portability table body rows",
           "% columns: artifact & <one per distro> & SHA-256 (short)"]
    for art, shas, identical in rows:
        cells = " & ".join(r"\ding{51}" if shas[i] and shas[i] == shas[ref] else r"\ding{55}"
                            for i in images)
        tex.append(f"\\texttt{{{art}}} & {cells} & \\texttt{{{(shas[ref] or '')[:10]}}} \\\\")
    (eval_results / "portability-table.tex").write_text("\n".join(tex) + "\n")

    print("\n".join(txt))
    print(f"\nWrote portability.{{txt,csv,tex}} to {eval_results}")
    return 0 if all_identical else 1


if __name__ == "__main__":
    sys.exit(main())
