plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kover)
    kotlin("plugin.serialization") version "2.1.20"
}

group = "carp.dsp.core"
version = "0.1.0"

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(17)
    jvm()

    sourceSets {
        commonMain {
            dependencies {
                implementation("dk.cachet.carp:carp-core-common")
                implementation("dk.cachet.carp:carp-core-data")
                implementation("dk.cachet.carp:carp-core-analytics")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
                implementation("com.charleskorn.kaml:kaml:0.61.0")
                implementation("io.github.oshai:kotlin-logging-jvm:7.0.3")

                // For coroutines support
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")

                // Ktor HTTP client for data retrieval
                implementation("io.ktor:ktor-client-core:2.3.7")
                implementation("io.ktor:ktor-client-content-negotiation:2.3.7")

                // Multiplatform datetime support
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.0")
            }
        }

        commonTest {
            dependencies {
                implementation(kotlin("test"))
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
            }
        }

        jvmMain {
            dependencies {
                // Ktor CIO engine for JVM
                implementation("io.ktor:ktor-client-cio:2.3.7")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
                implementation("io.github.oshai:kotlin-logging-jvm:7.0.3")
                // SLF4J backend — enables kotlin-logging output at runtime
                implementation("ch.qos.logback:logback-classic:1.5.6")
            }
        }

        jvmTest {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation("org.junit.jupiter:junit-jupiter-engine:5.10.0")
                implementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
            }
        }
    }
}

// ── Integration test filtering ───────────────────────────────────────────────
tasks.named<Test>("jvmTest") {
    if (System.getenv("CI") == "true" || System.getenv("SKIP_INTEGRATION") == "true") {
        exclude("**/integration/**")
    }
}

// ── Kover coverage configuration ─────────────────────────────────────────────
kover {
    reports {
        total {
            filters {
                excludes {
                    classes(
                        // Kotlin serialization companions generated by @Serializable
                        "carp.dsp.core.**\$Companion",
                        "**\$\$serializer",
                        "**\$serializer",

                        // Kotlin compiler synthetic helpers
                        "**\$DefaultImpls",
                        "**\$WhenMappings",
                        "**\$inlined*",
                        "**\$sam\$*",
                        "**\$copy\$default*",

                        // Test classes
                        "**Test",
                        "**Tests",
                        "**TestKt"
                    )
                    annotatedBy("carp.dsp.core.common.ExcludeFromCoverage")
                }
            }
        }
    }
}

